import boto3
from datetime import datetime, timedelta, timezone

def get_metric(cloudwatch, instance_id, metric_name, stat):
    end = datetime.now(timezone.utc)
    start = end - timedelta(minutes=15)

    response = cloudwatch.get_metric_statistics(
        Namespace="AWS/EC2",
        MetricName=metric_name,
        Dimensions=[{"Name": "InstanceId", "Value": instance_id}],
        StartTime=start,
        EndTime=end,
        Period=300,
        Statistics=[stat]
    )

    points = response.get("Datapoints", [])
    if not points:
        return None

    latest = sorted(points, key=lambda x: x["Timestamp"])[-1]
    return latest.get(stat)


def lambda_handler(event, context):
    region = event.get("region", "us-east-1")
    sns_topic_arn = event["sns_topic_arn"]
    instances = event.get("instances", [])

    cloudwatch = boto3.client("cloudwatch", region_name=region)
    sns = boto3.client("sns", region_name=region)

    checked_count = 0
    alert_count = 0
    results = []

    for item in instances:
        checked_count += 1

        instance_id = item["instance_id"]
        instance_name = item.get("instance_name", "No Name")
        cpu_limit = float(item.get("cpu_limit", 75))
        network_in_limit_mb = float(item.get("network_in_limit_mb", 500))
        network_out_limit_mb = float(item.get("network_out_limit_mb", 500))

        cpu = get_metric(cloudwatch, instance_id, "CPUUtilization", "Average")
        network_in = get_metric(cloudwatch, instance_id, "NetworkIn", "Sum")
        network_out = get_metric(cloudwatch, instance_id, "NetworkOut", "Sum")

        network_in_mb = round((network_in or 0) / 1024 / 1024, 2)
        network_out_mb = round((network_out or 0) / 1024 / 1024, 2)
        cpu_value = round(cpu, 2) if cpu is not None else None

        reasons = []

        if cpu_value is not None and cpu_value >= cpu_limit:
            reasons.append(f"CPU Usage crossed limit: {cpu_value}% >= {cpu_limit}%")

        if network_in_mb >= network_in_limit_mb:
            reasons.append(f"Network In crossed limit: {network_in_mb} MB >= {network_in_limit_mb} MB / 5 min")

        if network_out_mb >= network_out_limit_mb:
            reasons.append(f"Network Out crossed limit: {network_out_mb} MB >= {network_out_limit_mb} MB / 5 min")

        if reasons:
            alert_count += 1
            now_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

            message = f"""🚨 EC2 HIGH USAGE ALERT

Instance Name : {instance_name}
Instance ID   : {instance_id}
Region        : {region}
Time          : {now_time}

CPU Usage     : {cpu_value if cpu_value is not None else "No Data"}%
CPU Limit     : {cpu_limit}%

Network In    : {network_in_mb} MB / 5 min
Network Limit : {network_in_limit_mb} MB / 5 min

Network Out   : {network_out_mb} MB / 5 min
Network Limit : {network_out_limit_mb} MB / 5 min

Reason:
{chr(10).join(reasons)}

Generated by AWS EC2 Monitoring Lambda
"""

            sns.publish(
                TopicArn=sns_topic_arn,
                Subject=f"EC2 High Usage Alert - {instance_name}",
                Message=message
            )

            results.append({
                "instance_name": instance_name,
                "instance_id": instance_id,
                "status": "ALERT_SENT",
                "reasons": reasons
            })
        else:
            results.append({
                "instance_name": instance_name,
                "instance_id": instance_id,
                "status": "OK",
                "cpu": cpu_value,
                "network_in_mb": network_in_mb,
                "network_out_mb": network_out_mb
            })

    return {
        "status": "COMPLETED",
        "checked_servers": checked_count,
        "alert_servers": alert_count,
        "results": results
    }
